
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sadolnptzlfezdxjipqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZG9sbnB0emxmZXpkeGppcHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDQ3MzksImV4cCI6MjA2MTEyMDczOX0.YWMwjR7ZIYzauFwe4J-8vd64YM4qgoPuLEBYdgwWpZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
